filter:
    excluded_paths:
        - vendor/*
        - Tests/*

checks:
    php:
        code_rating: true
        duplication: true

build:
    tests:
        override:
            -
                command: phpunit
                coverage:
                    file: logs/coverage/clover.xml
                    format: clover
